### ISSUE TITLE
Hls support

### ISSUE THREAD

**Issue by c0b41** [JohannC/React-Web-Media-Player#2]
example usage with https://github.com/dailymotion/hls.js + https://github.com/mingxinstar/react-hls

**Comment by JohannC** [comment]
Hi,

I guess it might be possible because HLS work with an HTML video element. The solution could be to propose a "isHLS" option to the React-Web-Media-Player, and to add the HLS logic in "src/components/Medias/Channels/Video.js" when this option is true.

However, I don't know if the time navigation will work as it is "live streaming". If it is not compatible, adding an option to disable the time navigation could be a workaround.

Regards
